/**
 * lib/matn/uz.ts — QISM 1 §19
 *
 * Foydalanuvchiga ko'rinadigan barcha matn shu yerda. Kodga yozilmaydi —
 * shunda ikkinchi til kerak bo'lsa faqat shu faylning nusxasi olinadi.
 */

import type { XatoKod } from '@/lib/xato';

export const XATO_MATNI: Record<XatoKod, string> = {
  MATERIAL_YOQ: "Bu materialdan mos bo'lak topilmadi",
  LIMIT_OSHDI: "Mijozning qarz limiti oshib ketdi",
  CHEGIRMA_LIMITI: "Chegirma belgilangan chegaradan oshdi",
  STAVKA_YOQ: "Bu mahsulot turiga stavka belgilanmagan",
  KUN_YOPILGAN: "Kun yopilgan — bu sanaga yozuv kiritib bo'lmaydi",
  BOLAK_BAND: "Bo'lak boshqa pozitsiyaga band qilingan",

  PUL_NOTOGRI: "Pul qiymati noto'g'ri",
  KURS_NOTOGRI: "Valyuta kursi noto'g'ri",
  KURS_KERAK: "Dollarli hujjatda kurs kiritilishi shart",
  YAXLITLASH_NOTOGRI: "Yaxlitlash qadami noto'g'ri",
  NOLGA_BOLINDI: "Nolga bo'lish mumkin emas",
  OLCHOV_NOTOGRI: "O'lchov qiymati noto'g'ri",
  FORMULA_XATO: "Formulada xato bor",
  FORMULA_NOMALUM_OZGARUVCHI: "Formulada noma'lum o'zgaruvchi ishlatilgan",
  MUHIT_NOTOGRI: "Muhit o'zgaruvchilari to'liq emas",

  PAROL_QISQA: "Parol juda qisqa",
  KIRISH_NOTOGRI: "Telefon raqami yoki parol noto'g'ri",
  HISOB_BLOKLANGAN: "Hisob vaqtincha bloklangan",
  USTA_SAYTGA_KIRMAYDI: "Usta saytga kirmaydi — Telegram botdan foydalaning",
  SESSIYA_TUGAGAN: "Sessiya muddati tugagan, qayta kiring",
  RUXSAT_YOQ: "Bu amalga ruxsatingiz yo'q",

  FILIAL_TIKMAYDI: "Bu filialda ishlab chiqarish yo'q",
  FILIAL_NOFAOL: "Filial nofaol",

  NARX_NOTOGRI: "Narx qiymati noto'g'ri",
  KOEFFITSIENT_NOTOGRI: "Konversiya koeffitsienti noto'g'ri",
  BIRLIK_OZGARMAYDI: "Qoldiq bor ekan, birlikni o'zgartirib bo'lmaydi",
  RASM_NOTOGRI: 'Rasm formati noto‘g‘ri',
  RASM_KATTA: 'Rasm juda katta',
  MIQDOR_NOTOGRI: 'Miqdor noto‘g‘ri',
  TELEFON_BAND: 'Bu telefon raqami band',
  ROL_YOQ: 'Tanlangan rol topilmadi',
  YOZUV_YOQ: 'Yozuv topilmadi',
  KASSA_TAKRORLANDI: 'Bu xodimda bunday kassa allaqachon bor',
  SARF_NOTOGRI: 'Sarf noto‘g‘ri kiritilgan',
  BIRLIK_NOTOGRI: "Bunday o'lchov birligi yo'q",
  KONSTRUKTOR_XATO: "Mahsulot turi sozlamasida xato bor",
  TELEFON_NOTOGRI: "Telefon raqami noto'g'ri",
  MATERIAL_SAQLANMADI: "Materialni saqlab bo'lmadi",
  MATERIAL_TOPILMADI: "Material topilmadi",
  MIJOZ_SAQLANMADI: "Mijozni saqlab bo'lmadi",
  OCHIRILGANDA_BAND: "Bu qiymat o'chirilgan yozuvda band turibdi",
  MIJOZ_GURUH_BOR: 'Bunday nomli guruh allaqachon bor',
  MIJOZ_GURUH_TOPILMADI: 'Mijoz guruhi topilmadi',
  MIJOZ_GURUH_SAQLANMADI: "Guruhni saqlab bo'lmadi",
  MIJOZ_TOPILMADI: "Mijoz topilmadi",
  MIJOZ_DUBLIKAT: "Bunday mijoz allaqachon bor",
  MAHSULOT_SAQLANMADI: "Mahsulot turini saqlab bo'lmadi",
  MAHSULOT_TOPILMADI: "Mahsulot turi topilmadi",
  YETKAZIB_SAQLANMADI: "Yetkazib beruvchini saqlab bo'lmadi",
  YETKAZIB_TOPILMADI: "Yetkazib beruvchi topilmadi",
  TANNARX_NOTOGRI: "Tannarx hisobida noto'g'ri qiymat",
  KESIM_NOTOGRI: "Kesim ma'lumoti noto'g'ri",
  KIRIM_BOSH: "Kirim hujjatida bironta qator yo'q",
  KIRIM_SAQLANMADI: "Kirim hujjatini saqlab bo'lmadi",
  KIRIM_BOLAK_YETISHMAYDI: "Har rulon uchun eni va bo'yi kiritilishi kerak",
  KIRIM_ALLAQACHON_STORNO: "Bu hujjat allaqachon storno qilingan",
  KIRIM_TOPILMADI: "Kirim hujjati topilmadi",
  HARAKAT_BRAK_EMAS: "Bu yozuv hisobdan chiqarish emas",
  HARAKAT_TOPILMADI: "Ombor yozuvi topilmadi",
  BOLAK_ALLAQACHON_CHIQARILGAN: "Bu bo'lak allaqachon hisobdan chiqarilgan",
  BOLAK_TOPILMADI: "Bo'lak topilmadi",
  CHIQARISH_SAQLANMADI: "Hisobdan chiqarib bo'lmadi",
  CHIQARISH_SABAB_KERAK: "Sabab kiritilishi shart",
  CHIQARISH_ALLAQACHON_BEKOR: "Bu yozuv allaqachon bekor qilingan",
  INV_SABAB_KERAK: "Farq chiqdi — sababni tanlang",
  POZITSIYA_OTISH_MUMKIN_EMAS: "Pozitsiyani bu holatga o'tkazib bo'lmaydi",
  ISH_ALLAQACHON_OLINGAN: "Bu ish allaqachon olingan",
  ISH_SABAB_KERAK: "Sabab kiritilishi shart",
  BAND_TOPILMADI: "Bu pozitsiyada band qilingan material yo'q",
  QK_HOLAT_MOS_EMAS: "Qayta kesish faqat ish boshlangandan keyin so'raladi",
  QK_SOROV_OCHIQ: "Bu pozitsiyada hal qilinmagan so'rov bor",
  QK_TOPILMADI: "Qayta kesish so'rovi topilmadi",
  QK_ALLAQACHON_HAL: "Bu so'rov allaqachon hal qilingan",
  QK_USHLANMA_USTASIZ: "Ushlanma uchun ustaning haqi topilmadi",
  KASSA_TAKROR: "Bu hodisa uchun kassa yozuvi allaqachon bor",
  KASSA_TOPILMADI: "Kassa topilmadi",
  KASSA_NOFAOL: "Kassa yopilgan",
  KASSA_VALYUTA_MOS_EMAS: "Kassa valyutasi to'lov valyutasiga mos emas",
  KASSA_SUMMA_NOL: "Summa noldan farq qilishi kerak",
  KASSA_CHIQIM_MANFIY: "Chiqim summasi manfiy bo'lishi kerak",
  KASSA_SAQLANMADI: "Kassa yozuvini saqlab bo'lmadi",
  KASSA_YOZUV_TOPILMADI: "Kassa yozuvi topilmadi",
  KASSA_ALLAQACHON_STORNO: "Bu yozuv allaqachon storno qilingan",
  KASSA_SABAB_KERAK: "Storno sababi majburiy",
  KUN_IZOH_KERAK: "Farq bor — izoh kiritilishi shart",
  TOLOV_BOSH: "To'lov qatori kiritilmagan",
  TOLOV_MANFIY: "To'lov summasi noldan katta bo'lishi kerak",
  QAYTARISH_IZOH_KERAK: "Qaytarish izohi majburiy",
  XARAJAT_IZOH_KERAK: "Izoh majburiy",
  KASSA_ADMIN_EMAS: "Bu amal faqat admin kassasida bajariladi",
  KUN_SAQLANMADI: "Kunni yopib bo'lmadi",
  KUN_TOPILMADI: "Kun yozuvi topilmadi",
  KUN_YOPILMAGAN: "Bu kun yopilmagan",
  XARAJAT_KASSA_ZID: "Bu modda bo'yicha pul chiqmaydi (12.1)",
  XARAJAT_SAQLANMADI: "Xarajatni saqlab bo'lmadi",
  TOPSHIRIQ_TOPILMADI: "Topshiriq topilmadi",
  TOPSHIRIQ_ALLAQACHON_HAL: "Bu topshiriq allaqachon hal qilingan",
  POZITSIYA_TOPILMADI: "Buyurtma pozitsiyasi topilmadi",
  POZITSIYA_TAHRIRLANMAYDI: "Ish boshlangan — pozitsiya tahrirlanmaydi",
  BUYURTMA_TOPILMADI: "Buyurtma topilmadi",
  BUYURTMA_BOSH: "Savatda bironta pozitsiya yo'q",
  BUYURTMA_MIJOZ_KERAK: "Qarzga sotishda mijoz tanlanishi shart",
  BUYURTMA_FILIAL_KERAK: "Ishlab chiqaruvchi filialni tanlang",
  BUYURTMA_SAQLANMADI: "Buyurtmani saqlab bo'lmadi",
  INV_TOPILMADI: "Inventarizatsiya topilmadi",
  INV_YAKUNLANGAN: "Bu inventarizatsiya allaqachon yakunlangan",
  INV_BOSH: "Sanash varaqasida bironta qator yo'q",
  BOSHLANGICH_TAKROR: "Bu material uchun boshlang'ich qoldiq allaqachon kiritilgan",

  // 6-bosqich — filiallararo
  KOCHIRISH_TOPILMADI: "Ko'chirish hujjati topilmadi",
  KOCHIRISH_HOLAT: "Hujjatning hozirgi holatida bu amal bajarilmaydi",
  KOCHIRISH_BOSH: "Ko'chirishga bironta ham bo'lak tanlanmagan",
  KOCHIRISH_SABAB_KERAK: "Summa o'zgartirilsa sabab yozilishi shart",
  KOCHIRISH_AYNI_FILIAL: "Bo'lak boshqa filialda — o'z filialingiznikini tanlang",
  BOLAK_YOLDA: "Bo'lak yo'lda — qabul qilinmaguncha ishlatib bo'lmaydi",
  FILIAL_BALANS_NOL: "Filial balanslari yig'indisi nolga teng emas",

  // 20.2 — filial boshqaruvi
  FILIAL_TOPILMADI: 'Filial topilmadi',
  FILIAL_SAQLANMADI: 'Filial saqlanmadi',
  FILIAL_ISHLAB_CHIQARUVCHI_KERAK:
    "O'zi tikmaydigan filialga standart ishlab chiqarish filiali kerak",
  FILIAL_OZIGA_OZI: "Filial o'ziga o'zi buyurtma yubora olmaydi",
  FILIAL_BOSH_NOFAOL: "Bosh filialni nofaol qilib bo'lmaydi (20.2.2)",
  FILIAL_TAYANCH:
    "Bu filialga tayanadigan filiallar bor — avval ularning sozlamasini o'zgartiring",

  // 7-bosqich — bot (TZ 13)
  MIJOZ_ISM_KERAK: 'Ism kiritilmagan',
  MIJOZ_TELEFON_KERAK:
    "Telefon raqam kerak — «Telefon raqamni ulashish» tugmasini bosing (13.2)",
  MIJOZ_TELEFON_BAND:
    "Bu telefon boshqa Telegram hisobiga bog'langan — sotuvchiga murojaat qiling",
  XABAR_SAQLANMADI: "Xabarni navbatga qo'yib bo'lmadi",
  BOT_KIRISH_YOQ: "Bu bo'limga kirish huquqingiz yo'q",
  BOT_OQIM_BUZUQ: 'Buyurtma boshidan boshlansin — /start bosing',
  BOT_OQIM_TOLIQ_EMAS: "Pozitsiya to'liq emas: mato va o'lcham kerak",

  NOM_NOTOGRI: "Nom bo'sh yoki juda uzun",
  SAQLANMADI: 'Saqlanmadi — qaytadan urinib ko‘ring',
};

export const BIRLIK_MATNI = {
  SM: 'sm',
  M: 'm',
  KV_M: 'kv.m',
  DONA: 'dona',
} as const;

export const VALYUTA_MATNI = {
  SOM: "so'm",
  USD: 'dollar',
} as const;
